package io.github.omerbar4.paymentledger.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * A monetary transaction (payment or refund). Rows are created through an
 * {@code INSERT ... ON CONFLICT (idempotency_key) DO NOTHING} statement, so the identifier is
 * assigned by the application rather than generated by JPA.
 */
@Entity
@Table(name = "transactions")
public class LedgerTransaction {

    @Id
    private UUID id;

    @Column(name = "idempotency_key", nullable = false, updatable = false)
    private String idempotencyKey;

    @Column(name = "request_hash", nullable = false, length = 64, updatable = false)
    private String requestHash;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16, updatable = false)
    private TransactionType type;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private TransactionStatus status;

    @Column(name = "source_account_id", nullable = false, updatable = false)
    private UUID sourceAccountId;

    @Column(name = "destination_account_id", nullable = false, updatable = false)
    private UUID destinationAccountId;

    @Column(nullable = false, precision = 19, scale = 4, updatable = false)
    private BigDecimal amount;

    @Column(nullable = false, length = 3, updatable = false)
    private String currency;

    @Column(length = 255, updatable = false)
    private String description;

    @Column(name = "failure_reason")
    private String failureReason;

    @Column(name = "refund_of_id", updatable = false)
    private UUID refundOfId;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected LedgerTransaction() {
    }

    private LedgerTransaction(String idempotencyKey, String requestHash, TransactionType type,
                              UUID sourceAccountId, UUID destinationAccountId, BigDecimal amount,
                              String currency, String description, UUID refundOfId) {
        this.id = UUID.randomUUID();
        this.idempotencyKey = idempotencyKey;
        this.requestHash = requestHash;
        this.type = type;
        this.status = TransactionStatus.PENDING;
        this.sourceAccountId = sourceAccountId;
        this.destinationAccountId = destinationAccountId;
        this.amount = amount;
        this.currency = currency;
        this.description = description;
        this.refundOfId = refundOfId;
        this.createdAt = Instant.now();
        this.updatedAt = this.createdAt;
    }

    public static LedgerTransaction newPayment(String idempotencyKey, String requestHash,
                                               UUID sourceAccountId, UUID destinationAccountId,
                                               BigDecimal amount, String currency, String description) {
        return new LedgerTransaction(idempotencyKey, requestHash, TransactionType.PAYMENT,
                sourceAccountId, destinationAccountId, amount, currency, description, null);
    }

    /** A refund moves the original amount back: from the original destination to the original source. */
    public static LedgerTransaction newRefund(String idempotencyKey, String requestHash, LedgerTransaction original) {
        return new LedgerTransaction(idempotencyKey, requestHash, TransactionType.REFUND,
                original.destinationAccountId, original.sourceAccountId, original.amount,
                original.currency, "Refund of " + original.id, original.id);
    }

    public boolean isRefundable() {
        return type == TransactionType.PAYMENT && status == TransactionStatus.POSTED;
    }

    public void markPosted() {
        transition(TransactionStatus.PENDING, TransactionStatus.POSTED);
    }

    public void markFailed(String reason) {
        transition(TransactionStatus.PENDING, TransactionStatus.FAILED);
        this.failureReason = reason;
    }

    public void markRefunded() {
        if (type != TransactionType.PAYMENT) {
            throw new IllegalStateException("Only payments can be refunded");
        }
        transition(TransactionStatus.POSTED, TransactionStatus.REFUNDED);
    }

    private void transition(TransactionStatus expected, TransactionStatus next) {
        if (status != expected) {
            throw new IllegalStateException("Cannot move transaction " + id + " from " + status + " to " + next);
        }
        this.status = next;
        this.updatedAt = Instant.now();
    }

    public UUID getId() {
        return id;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public String getRequestHash() {
        return requestHash;
    }

    public TransactionType getType() {
        return type;
    }

    public TransactionStatus getStatus() {
        return status;
    }

    public UUID getSourceAccountId() {
        return sourceAccountId;
    }

    public UUID getDestinationAccountId() {
        return destinationAccountId;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public String getCurrency() {
        return currency;
    }

    public String getDescription() {
        return description;
    }

    public String getFailureReason() {
        return failureReason;
    }

    public UUID getRefundOfId() {
        return refundOfId;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
